#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Daiki Kurokawa
# SPDX-License-Identifier: BSD-3-Clause  
import sys
  
plus = 0  # plusは和 mltは積 cntはループの回数#
mlt = 1
cnt =0
for line in sys.stdin:
    try:#整数ちなら？#
        plus += int(line)   
        mlt *= int(line)
        cnt += 1
    except:#少数があるときは？＃
          plus += float(line)
          mlt *= float(line)
          cnt += 1.0

#和、積、平均#
print(plus,mlt,float(plus) /cnt)

