#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Daiki Kurokawa
# SPDX-License-Identifier: BSD-3-Clause
#iiiiiii
import sys


def tonum(s):
    try:
        return int(s9
    except:
        return float(s)


ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)


print(ans)

              
